---
title: "Demo report with Regression Tables"
author: "Liming Wang"
date: "10/22/2017"
output: rmarkdown::word_document
#output: rmarkdown::html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

# `mpg` models

```{r, echo=FALSE}
require(dplyr)
require(texreg)
require(captioner)

tab_path <- "tabs"
if (!file.exists(tab_path))
  dir.create(tab_path)

table_nums <- captioner(prefix = "Table", suffix = ".")
table1_cap <- table_nums("mpg_models", "OLS regression for mileage")
table1_num <- table_nums("mpg_models", display="cite")
```

We are interested in modeling `mpg` for our first two models and `r table1_num` shows the results.

```{r table1, echo=FALSE}
knitr::kable(tibble(placeholder=1, to_be_replaced=1), caption=table1_cap)
htmlreg(list(lm(mpg ~ wt, data=mtcars), 
             lm(mpg ~ wt + cyl, data=mtcars)), 
        file=file.path(tab_path, paste0(table1_num, ".html")),
        doctype = TRUE, html.tag = TRUE, 
        caption = "", 
        caption.above = TRUE)
```

# `hp` models

```{r, echo=FALSE}
table2_cap <- table_nums("hp_models", "OLS regression for horse power")
table2_num <- table_nums("hp_models", display="cite")
```

We are interested in modeling `hp` for our last two models and `r table_nums("hp_models", display="cite")` shows the results.

```{r table2, echo=FALSE}
knitr::kable(tibble(placeholder=1, to_be_replaced=1), caption=table2_cap)
htmlreg(list(lm(hp ~ wt, data=mtcars), 
             lm(hp ~ wt + cyl, data=mtcars)), 
        file=file.path(tab_path, paste0(table2_num, ".html")),
        doctype = TRUE, html.tag = TRUE, 
        caption = "", 
        caption.above = TRUE)
```

